// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-GckfL8YglCMJoShTiw0RndB4xxnisgQ',
    appId: '1:957890556594:web:e22e4555af2e48500a0fab',
    messagingSenderId: '957890556594',
    projectId: 'travoapps-b31c4',
    authDomain: 'travoapps-b31c4.firebaseapp.com',
    storageBucket: 'travoapps-b31c4.appspot.com',
    measurementId: 'G-EBQB2JXGQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBlH2F4HdwO705LYAcIL72pOx7W0tI7g0',
    appId: '1:957890556594:android:b2dee882a107fd1c0a0fab',
    messagingSenderId: '957890556594',
    projectId: 'travoapps-b31c4',
    storageBucket: 'travoapps-b31c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_OoIK9CWccHUs099SDAB4SPbZhEBcKZQ',
    appId: '1:957890556594:ios:6e624d64b4222b740a0fab',
    messagingSenderId: '957890556594',
    projectId: 'travoapps-b31c4',
    storageBucket: 'travoapps-b31c4.appspot.com',
    androidClientId: '957890556594-c21gmn0keuu0e30rq493fmstlbqv3ocf.apps.googleusercontent.com',
    iosClientId: '957890556594-vtv3atiilr38icsathi8ies8soreri3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNhuNguyen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_OoIK9CWccHUs099SDAB4SPbZhEBcKZQ',
    appId: '1:957890556594:ios:770d0f3f5f726d070a0fab',
    messagingSenderId: '957890556594',
    projectId: 'travoapps-b31c4',
    storageBucket: 'travoapps-b31c4.appspot.com',
    androidClientId: '957890556594-c21gmn0keuu0e30rq493fmstlbqv3ocf.apps.googleusercontent.com',
    iosClientId: '957890556594-65i88vu11mj2shimu49e7h9he9arfqi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNhuNguyen.RunnerTests',
  );
}
